on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check-Bioc-devel

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '4.1'}
          - {os: macOS-latest, r: '4.1'}
          - {os: ubuntu-18.04, r: '4.1', rspm: "https://demo.rstudiopm.com/all/__linux__/bionic/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{secrets.PAT}}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install R packages for CI
        run: |
          install.packages(c('remotes', 'BiocManager'))
          remotes::install_github('r-hub/sysreqs')
          BiocManager::install(version = "devel", ask = FALSE)
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories()), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
          # libcurl4 for Rhtslib
        run: |
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          sudo apt-get install libcurl4-openssl-dev libglpk-dev

      - name: Install R dependencies
        run: |
          remotes::install_github("adw96/breakaway", repos = BiocManager::repositories())
          remotes::install_github("FelixErnst/SEtup", repos = BiocManager::repositories())
          remotes::install_github("FelixErnst/MicrobiomeExperiment", repos = BiocManager::repositories())
          BiocManager::install(remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())$package)
          remotes::install_cran(c("rcmdcheck","covr","magick"))
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Test coverage
        if: matrix.config.os == 'ubuntu-18.04' && matrix.config.r == '3.6'
        run: |
          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
